language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -r requirements.txt

download:
  - sh ./data/download.sh

script:
  - python -c "from pysfitter import *"
  - python -m pytest --cov=./

after_success:
  - codecov --token=$CODECOV_TOKEN

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
